### ISSUE TITLE
Writing a song to the Roomba

### ISSUE THREAD

**Issue by minermartijn** [thehookup/MQTT-Roomba-ESP01#15]
First of all, thank you so much for this code.
I got this running on my roomba, and it worked great untill I tried to fix the cables and broke the port.

Guess im going to have to find a cheap second hand 500 series so i can try again.

I was wondering if you or anyone else thats using this code has figured out how i could program a song onto the roomba.
Tried to make a function myself example showed below, its for jingle bells and should be correct. 
But it seems to now work. Can anyone help me?

I really want to program The Imperial March, and have it play that song everytime it starts cleaning.
Just for fun ofcourse, and maybe find some darth vader decals for the roomba haha.

I made an extra payload with mqtt, that starts this installl. and another that starts the song. But its not working.

`void jinglesetupb() {
 Serial.write(128);
 Serial.write(131);
 Serial.write(140);
 Serial.write(2);
 Serial.write(16);
 Serial.write(76);
 Serial.write(16);
 Serial.write(76);
 Serial.write(16);
 Serial.write(76);
 Serial.write(32);
 Serial.write(76);
 Serial.write(16);
 Serial.write(76);
 Serial.write(16);
 Serial.write(76);
 Serial.write(32);
 Serial.write(76);
 Serial.write(16);
 Serial.write(79);
 Serial.write(16);
 Serial.write(72);
 Serial.write(16);
 Serial.write(74);
 Serial.write(16);
 Serial.write(76);
 Serial.write(32);
 Serial.write(77);
 Serial.write(16);
 Serial.write(77);
 Serial.write(16);
 Serial.write(77);
 Serial.write(16);
 Serial.write(77);
 Serial.write(32);
 Serial.write(77);
 Serial.write(16);
 Serial.write(140);
 Serial.write(3);
 Serial.write(7);
 Serial.write(76);
 Serial.write(16);
 Serial.write(76);
 Serial.write(32);
 Serial.write(79);
 Serial.write(16);
 Serial.write(79);
 Serial.write(16);
 Serial.write(77);
 Serial.write(16);
 Serial.write(74);
 Serial.write(16);
 Serial.write(72);
 Serial.write(32);
}`

**Comment by minermartijn** [comment]
I have not had a change to test this, because of my failure to NOT break my roomba port.
But maybe this is a better way? Can anyone tell me if im going in the right direction?

`void songs() {
  byte Song0[17]={140,0,7,31,60,43,55,55,50,67,45,79,40,91,35,103,30};
  byte Song1[35]={140,1,16, 36,20, 37,20, 0,40,  36,20, 37,20, 0,30,  36,20, 37,20, 0,20,  36,20, 37,20, 0,10,  36,20, 37,20, 0,5,  38,64}; //Jaws
  byte Song2[13]={140,2,5,79,48,81,48,77,48,65,50,72,64}; //Strange Encounters 1
  byte Song3[13]={140,3,5,69,48,71,48,67,48,55,48,62,64}; //Strange Encounters
  Serial.write(Song0,17);
  Serial.write(Song1,35);
  Serial.write(Song2,13);
  Serial.write(Song3,13);
  client.publish("checkIn/roomba", "Songs Installed");
}`

**Comment by minermartijn** [comment]
Still no cigar.... So still looking for a solution if anyone has one.

**Comment by tareko** [comment]
Out of curiosity, how is this closed as completed? Was there an associated commit?

**Comment by minermartijn** [comment]
I Closed it myself, because i figured it out. Forgot i wanted to post a update on that sorry.
the following is the code that writes and plays the song. 

```
void imperialmarch() {
  byte Song1[35]={140,1,16,
    81, 32,  // C
    81, 32,  // G
    81, 32,  // F
    77, 32,  // E
    84, 16,  // D
    81, 16,  // C
    77, 32,  // G
    84, 16,  // F
    81, 16,  // E
    88, 32,  // E
    88, 32,  // E
    88, 32,  // E
    89, 32,  // F
    84, 16,  // C
    80, 32,  // G#
    77, 32   // F
  };

  byte Song2[7]={140,2,2,
    77, 16,  // C
    81, 32   // A
  };

  Serial.write(128);
  delay(50);
  Serial.write(132);
  delay(50);
  Serial.write(Song1,35);
  Serial.write(Song2,7);
  delay(500);
  byte Part1[2]={141,1};
  Serial.write(Part1,2);
  delay(7300);
  byte Part2[2]={141,2};
  Serial.write(Part2,2);
}
```
